"""empty message

Revision ID: 0a7e4059e1d0
Revises: 9b75d70ef09c
Create Date: 2026-06-26 16:22:53.129692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7e4059e1d0'
down_revision = '9b75d70ef09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pp_filename',
               existing_type=sa.VARCHAR(length=64),
               nullable=False, server_default="default_pp.png")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pp_filename',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
