"""add match model

Revision ID: 4061199200f1
Revises: 44ad7c818e01
Create Date: 2026-06-26 18:26:55.395411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4061199200f1'
down_revision = '44ad7c818e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player1_rank', sa.Integer(), nullable=False),
    sa.Column('player2_rank', sa.Integer(), nullable=False),
    sa.Column('sets', sa.JSON(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
