"""add email to user

Revision ID: 59796d7f3c35
Revises: dba41200c592
Create Date: 2026-06-26 12:09:28.900801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59796d7f3c35'
down_revision = 'dba41200c592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), server_default='email@email.cz', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
