"""empty message

Revision ID: 60814cfc47b9
Revises: 59796d7f3c35
Create Date: 2026-06-26 15:31:40.976604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60814cfc47b9'
down_revision = '59796d7f3c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False, server_default="Jmeno Prijmeni"))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
