"""empty message

Revision ID: 692a574b646a
Revises: 0a7e4059e1d0
Create Date: 2026-06-26 17:04:44.834052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692a574b646a'
down_revision = '0a7e4059e1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
