"""add pp_filename to user

Revision ID: 9b75d70ef09c
Revises: 60814cfc47b9
Create Date: 2026-06-26 15:53:38.876858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b75d70ef09c'
down_revision = '60814cfc47b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pp_filename', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pp_filename')

    # ### end Alembic commands ###
